# sudo for docker
sudo: required
dist: xenial

services:
  - docker

env:
  global:
    - VERSION=1.53.1
    - DOCKER_USERNAME=ablyler
    - DOCKER_REPONAME=librenms
    - DOCKER_LOGIN=ablyler
    - QUAY_USERNAME=librenms
    - QUAY_REPONAME=librenms
    - QUAY_LOGIN=librenms+travis

# Only clone the most recent commit.
git:
  depth: 1

# install qemu-user before running docker build
before_install:
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234

addons:
  apt:
    packages:
      - docker-ce

script: ./build.sh

# Don't email me the results of the test runs.
notifications:
  email: false