sudo: required

services:
  - docker

env:
  global:
    - VERSION=1.53.1
    - DOCKER_USERNAME=ablyler
    - DOCKER_REPONAME=librenms
    - DOCKER_LOGIN=ablyler
    - QUAY_USERNAME=librenms
    - QUAY_REPONAME=librenms
    - QUAY_LOGIN=librenms+travis

before_install:
  - sudo apt-get update
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234
  - docker --version

addons:
  apt:
    packages:
      - docker-ce

script: ./build.sh
